config/routes.rb
Rails.application.routes.draw do
  get 'items/create'

  devise_for :users

  resources :users do
    resources :items, only: [:create, :destroy]
  end

  get 'about' => 'welcome#about'

  get 'welcome' => 'welcome#index'

  authenticated :user do
    root "users#index", as: :authenticated_root
  end

  namespace :api, defaults: { format: :json } do
    resources :users do
       resources :items, only: [:create, :update]
    end
    resources :items, only: [:update]
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  default_scope { order('created_at DESC') }

  validates :description, length: { minimum: 3 }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :confirmable, :validatable

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApiController
before_action :check_auth

def index
  items = Item.all
  render json: items, each_serializer: ItemSerializer
end

def create
  @user = User.find(params[:user_id])
  @item = @user.items.build(item_params)

  if @item.save
    render json: @item
  else
    render json: { errors: @item.errors.full_messages }, status: :unprocessable_entity
  end
end

def update
  item = Item.find(params[:id])
  if item.update(item_params)
    render json: item
  else
    render json: { errors: item.errors.full_messages }, status: :unprocessable_entity
  end
end

private
def item_params
  params.require(:item).permit(:description, :completed, :active, :expired)
end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController
  before_action :check_auth

  def index
    users = User.all
    render json: users, each_serializer: UserSerializer
  end

  def create
    user = User.new(user_params)
    if user.save
      render json: user
    else
      render json: { errors: user.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    begin
      user = User.find(params[:id])
      user.destroy
      render json: {}, status: :no_content
    rescue ActiveRecord::RecordNotFound
      render :json => {}, :status => :not_found
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token

  private
  def check_auth
    authenticate_or_request_with_http_basic do |username,password|
      resource = User.find_by_email(username)
      if resource.valid_password?(password)
        sign_in :user, resource
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  respond_to :html, :js

  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if @item.save
      flash[:notice] = "To-do was saved."
      redirect_to current_user
    else
      flash[:alert] = "There was an error saving the to-do. Please try again."
      redirect_to current_user
    end
  end

  def destroy
    @item = Item.find(params[:id])

    if @item.destroy
      flash[:notice] = "'#{@item.description}' has been completed."
      redirect_to current_user
    else
      flash[:alert] = "Error completing to-do. Please try again."
      redirect_to current_user
    end
end

  private

  def item_params
    params.require(:item).permit(:description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @item = Item.new
  end

  def update
    @user = User.find(params[:id])
    @user.assign_attributes(user_params)

    if @user.save
      flash[:notice] = "user was updated."
      redirect_to current_user
    else
      flash.now[:alert] = "There was an error saving the user. Please try again."
      redirect_to current_user
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :private)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [@user, @item] do |f| %>
  <div class="form-group">
    <%= f.label 'New to-do' %>
    <%= f.text_field :description, class: 'form-control', placeholder: "Enter to-do" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<% @user.items.each do |item| %>
  <div class="media" id="item">
    <div class="media-body">
      <h4 class="media-heading">
        <% if current_user == @user %>
          <%= link_to "", [current_user, item], method: :delete, remote: true, class: 'glyphicon glyphicon-ok' %>:
        <% end %>
        <%= item.description %>
      </h4>
      <p>
        created <strong><%= time_ago_in_words(item.created_at) %></strong> ago.</br>
        In <strong><%= distance_of_time_in_words(Time.now, item.created_at + 7.days )%></strong> item will be deleted.
      </p>
    </div>
  </div>
<% end %>

app/views/items/destroy.js.erb
$('#item').click(function(){
    $('#item').remove();
})

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Blocitoff", welcome_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <li class="pull-right"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <li class="pull-right"><%= link_to 'Edit profile', edit_user_registration_path %><li>
        <% else %>
          <li class="pull-right"><%= link_to "Sign In", new_user_session_path %></li>
          <li class="pull-right"><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
      <% if flash[:notice] %>
        <div class='alert alert-success alert-dismissable'>
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class='alert alert-warning alert-dismissable'>
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <%= flash[:alert] %>
        </div>
      <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/index.html.erb
<div class="jumbotron">
  <h1>Blocitoff</h1>
  <p>A resource for managing to-do lists!</p>
</div>
<h2>Users</h2>
<div class="col-md-8">
<% @users.each do |user| %>
  <% if !user.private || current_user == user %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to user.username, user %>
        </h4>
      </div>
    </div>
  <% end %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="col-md-12">
  <div class="media jumbotron">
    <% avatar_url = @user.avatar_url(86) %>
    <% if avatar_url %>
      <div class="media-left">
        <%= image_tag avatar_url, class: 'media-object' %>
      </div>
      <% end %>
    <div class="media-body">
      <h2 class="media-heading"><%= @user.username %></h2>
      <h4>email: <%= @user.email %></h4>
      <h5>Member since: <%= @user.created_at.strftime('%x') %></h5>
    </div>
  </div>
  <div class='private'>
    <%= form_for [@user] do |f| %>
      <% if current_user == @user %>
        <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Make profile private
        <% end %>
        <div class="form-group">
          <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
      <% end %>
    <% end %>
  </div>

  <% if current_user == @user %>
    <div class="col-md-8">
      <%= render partial: 'items/form' %>
    </div>
  <% end %>

  <div class="col-md-8">
    <%= render partial: 'items/item' %>
  </div>
</div>

app/views/welcome/about.html.erb
<div class="jumbotron">
  <h1>About Blocitoff</h1>
  <p>TBD</p>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Blocitoff</h1>
  <p>A resource for managing to-do lists!</p>
</div>